server:
  port: 9000
  context-path: /web-boss


spring:
  dubbo:
    application.name: web-boss
#    registry.address: zookeeper://47.111.22.77:2181
    registry.address: nacos://47.111.22.77:8848
    protocol:
      name: dubbo
      port: 20880
    scan: com.yfancy

  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    suffix: .html
logging:
  config: classpath:config/logback-dev.xml

