server:
  port: 8082
  context-path: /web-boss
spring:
  dubbo:
    application.name: web-boss
    registry.address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20882
    scan: com.yfancy
logging:
  config: classpath:config/logback-online.xml