server:
  port: 9898

spring:
  # datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.111.22.77:3306/vip?characterEncoding=utf-8
    username: root
    password: 123456
    maxActive: 20
    initialSize: 1
    maxWait: 60000
  aop:
    proxy-target-class: true
  # dubbo
  dubbo:
    application.name: service-vip
    registry.address: zookeeper://47.111.22.77:2181
    protocol:
      name: dubbo
      port: 20888
    scan: com.yfancy


# mybatis
#mybatis:
#  typeAliasesPackage: com.yfancy.common.base.entity
#  mapperLocations: classpath:mapper/*.xml
logging:
  config: classpath:config/logback-dev.xml