server:
  port: 9898
  context-path: /admin

spring:
  dubbo:
    application.name: yfancy-timer
    registry.address: zookeeper://47.111.22.77:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.yfancy
logging:
  config: classpath:config/logback-online.xml