server:
  port: 6600

spring:
  dubbo:
    application.name: web-timer
#    registry.address: zookeeper://47.111.22.77:2181
    registry.address: nacos://47.111.22.77:8848
    protocol:
      name: dubbo
      port: 20880
    scan: com.yfancy
logging:
  config: classpath:config/logback-dev.xml

